# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-02 10:19
from __future__ import unicode_literals

import adhocracy4.maps.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4projects', '0018_add_location_and_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='point',
            field=adhocracy4.maps.fields.PointField(blank=True, null=True, verbose_name='Location of your Project'),
        ),
    ]
